name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk \
          python3-pip python3-setuptools python3-wheel \
          python3-virtualenv libtool libffi-dev libssl-dev \
          libsqlite3-dev zlib1g-dev

        python3 -m pip install --upgrade pip
        pip install cython buildozer

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android && echo '### User Agreements' > ~/.android/repositories.cfg
        yes | buildozer android update

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyKivyApp
        path: bin/*.apk
