name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk \
          python3-pip python3-setuptools python3-wheel \
          python3-virtualenv libtool libffi-dev libssl-dev \
          libsqlite3-dev zlib1g-dev

    - name: Build APK
      run: |
        pip install --user buildozer
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4.3.1
      with:
        name: MyKivyApp
        path: bin/*.apk


